(block) @fold
(type_alias_declaration) @fold
(struct_declaration) @fold
(enum_declaration) @fold
(trait_declaration) @fold
(actor_struct_declaration) @fold
(actor_trait_declaration) @fold
(impl_declaration) @fold
(import_group) @fold
(case_expression) @fold
(if_expression) @fold
(loop_expression) @fold
(for_expression) @fold
(while_expression) @fold
(list_expression) @fold
(map_expression) @fold
